name: Create Merge PR Upstream

on:
  workflow_call:
    inputs:
      labels:
        type: string
        description: |
          Comma separated list of lables to attach to the PR. 
          Adds automerge label by default.
        default: automerge
        required: false
    secrets:
      BONITA_CI_PAT:
        required: true

env:
  GH_TOKEN: ${{ secrets.BONITA_CI_PAT }}
jobs:
  create-pr:
    runs-on: ubuntu-22.04
    steps:
      - name: Determine upstream branch
        id: upstream-branch
        run: echo "ref=${{ fromJson(vars.SUPPORTED_BRANCHES).upstream-branch[github.ref_name] }}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BONITA_CI_PAT }}
      - id: create-pr
        run: >
          pr_url=$(gh pr create
          --base ${{ steps.upstream-branch.outputs.ref }}
          --assignee ${{ github.actor }}
          --title "[merge] ${{ github.ref_name}} into ${{ steps.upstream-branch.outputs.ref }}"
          --body "Pull request opened automatically. Use Merge Pull Request action (DO NOT SQUASH).")
          && echo "pr-url=$pr_url" >> "$GITHUB_OUTPUT"
      - id: enable-auto-merge
        run: >
          gh pr merge 
          --auto
          --merge
          ${{ steps.create-pr.outputs.pr-url }}
      - id: add-pr-labels
        if: ${{ inputs.labels != '' }}
        run: |
          IFS="," read -a myarray <<< ${{ inputs.labels }}
          for i in "${myarray[@]}"; do
            gh pr edit ${{ steps.create-pr.outputs.pr-url }}  --add-label ${i}
          done